# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/clone-hmpdups_/recipe, last modified Thu Jan 20 11:51:46 2022
# ------------------------------------------------

package:
  name: cffi
  version: 1.15.0
source:
  patches:
    - 0001-Link-to-dl-library.patch
    - setup-linux.patch
  sha256: 920f0d66a896c2d99f0adbb391f990a84091179542c205fa53ce5787aff87954
  url: https://pypi.io/packages/source/c/cffi/cffi-1.15.0.tar.gz
build:
  missing_dso_whitelist: null
  number: '1'
  script: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-2p6q7e2r/cffi_1642701115063/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: py37hc55c11b_1
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_23
    - clang 12.0.0 hecd8cb5_2
    - clang-12 12.0.0 default_hfcad0e5_2
    - clang_osx-64 12.0.0 h7ad7729_2
    - clangxx 12.0.0 default_hfcad0e5_2
    - compiler-rt 12.0.0 hd87ff74_2
    - compiler-rt_osx-64 12.0.0 hfb26b64_2
    - ld64_osx-64 530 h70f3046_23
    - ldid 2.1.2 h2d21305_2
    - libclang-cpp12 12.0.0 default_hfcad0e5_2
    - libcxx 12.0.0 h2f01273_0
    - libllvm12 12.0.0 h9b2ccf5_3
    - llvm-tools 12.0.0 h9b2ccf5_3
    - patch 2.7.6 h1de35cc_1001
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.11 h4dc903c_4
  host:
    - ca-certificates 2021.10.26 hecd8cb5_2
    - certifi 2021.10.8 py37hecd8cb5_2
    - libcxx 12.0.0 h2f01273_0
    - libffi 3.3 hb1e8313_2
    - ncurses 6.3 hca72f7f_2
    - openssl 1.1.1m hca72f7f_0
    - pip 21.2.2 py37hecd8cb5_0
    - python 3.7.11 h88f2d9e_0
    - readline 8.1.2 hca72f7f_1
    - setuptools 58.0.4 py37hecd8cb5_0
    - sqlite 3.37.0 h707629a_0
    - tk 8.6.11 h7bc2e8c_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h1de35cc_0
    - zlib 1.2.11 h4dc903c_4
  run:
    - libffi >=3.3
    - pycparser
    - python >=3.7,<3.8.0a0
test:
  commands:
    - pip check
  imports:
    - _cffi_backend
    - cffi
  requires:
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://foss.heptapod.net/pypy/cffi
  doc_source_url: https://foss.heptapod.net/pypy/cffi/-/tree/branch/default/doc/source
  doc_url: https://cffi.readthedocs.io/en/latest/
  home: http://cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - inducer
    - mingwandroid
    - ocefpaf
