ignore_build_only_deps:
- python
- numpy
extend_keys:
- extend_keys
- ignore_build_only_deps
- ignore_version
- pin_run_as_build
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
tk:
- '8.6'
VERBOSE_AT:
- V=1
clang_variant:
- clang
r_base:
- '3.5'
python:
- '3.6'
- '3.7'
- '3.9'
- '3.8'
lzo:
- '2'
macos_machine:
- x86_64-apple-darwin13.4.0
CONDA_BUILD_SYSROOT:
- /opt/MacOSX10.14.sdk
gmp:
- '6.1'
libkml:
- '1.3'
gstreamer:
- '1.14'
geos:
- 3.8.0
libdap4:
- '3.19'
libnetcdf:
- '4.6'
cyrus_sasl:
- 2.1.26
dummy_var:
- '0'
giflib:
- '5'
perl:
- '5.26'
r_version:
- 3.5.0
fontconfig:
- '2.13'
glib:
- '2'
cxx_compiler:
- clang_bootstrap
llvm_variant:
- llvm
vc:
- '14'
target_platform:
- osx-64
libgsasl:
- '1.8'
dbus:
- '1'
sqlite:
- '3'
qtwebkit:
- 'true'
libtiff:
- '4.1'
libwebp:
- 1.0.0
boost_cpp:
- '1.73'
python_implementation:
- cpython
gnu:
- 2.12.2
mkl:
- '2021'
cudatoolkit:
- '9.0'
macos_min_version:
- '10.9'
expat:
- '2.2'
xz:
- '5'
hdf5:
- 1.10.6
proj:
- 6.2.1
channel_targets:
- defaults
libxslt:
- '1.1'
serf:
- 1.3.9
icu:
- '58'
python_impl:
- cpython
fortran_compiler:
- gfortran
noarch_python:
- python
r_implementation:
- r-base
libgdal:
- '3.0'
hdfeos2:
- '2.20'
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
apr:
- 1.6.3
libpng:
- '1.6'
libgd:
- 2.2.5
rust_compiler_version:
- 1.46.0
freetype:
- '2.10'
VERBOSE_CM:
- VERBOSE=1
zlib:
- '1.2'
openblas:
- 0.3.3
jpeg:
- '9'
c_compiler_version:
- 10.0.0
hdf4:
- '4.2'
libxml2:
- '2.9'
boost:
- '1.73'
hdfeos5:
- '5.1'
blas_impl:
- openblas
- mkl
pixman:
- '0.30'
lua:
- '5'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
gst_plugins_base:
- '1.14'
MACOSX_SDK_VERSION:
- '10.12'
mpfr:
- '4'
openssl:
- 1.1.1
cpu_optimization_target:
- nocona
c_compiler:
- clang_bootstrap
libprotobuf:
- 3.11.2
rust_compiler:
- rust
openjpeg:
- '2.3'
readline:
- '8.0'
proj4:
- 5.2.0
libffi:
- '3.3'
cairo:
- '1.14'
numpy:
- '1.16'
g2clib:
- '1.6'
harfbuzz:
- '2.4'
bzip2:
- '1.0'
cxx_compiler_version:
- 10.0.0
zip_keys: []
