# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_clone-snajz8fr/recipe, last modified Wed Apr  6 02:33:40 2022
# ------------------------------------------------

package:
  name: setuptools
  version: 61.2.0
source:
  patches:
    - patches/0002-disable-downloads-inside-conda-build.patch
    - patches/0006-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
    - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch
    - patches/0019-Use-ranlib-from-env-if-env-variable-is-set.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
  sha256: c3d4e2ab578fbf83775755cd76dae73627915a22832cf4ea5de895978767833b
  url: https://pypi.io/packages/source/s/setuptools/setuptools-61.2.0.tar.gz
build:
  number: '0'
  string: py37hecd8cb5_0
requirements:
  build:
    - patch 2.7.6 h1de35cc_1001
  host:
    - ca-certificates 2022.3.29 hecd8cb5_0
    - certifi 2021.10.8 py37hecd8cb5_2
    - libcxx 12.0.0 h2f01273_0
    - libffi 3.3 hb1e8313_2
    - ncurses 6.3 hca72f7f_2
    - openssl 1.1.1n hca72f7f_0
    - python 3.7.13 hdfd78df_0
    - readline 8.1.2 hca72f7f_1
    - sqlite 3.38.2 h707629a_0
    - tk 8.6.11 h7bc2e8c_0
    - xz 5.2.5 h1de35cc_0
    - zlib 1.2.11 h4dc903c_4
  run:
    - certifi >=2016.9.26
    - python >=3.7,<3.8.0a0
test:
  imports:
    - pkg_resources
    - setuptools
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
  doc_url: https://setuptools.pypa.io/en/latest/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d230857c-c81c-4375-8801-13385340abaa
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/setuptools-feedstock.git
  sha: 8bf94ce0f61569fa46790641b636d9884658a203
