# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/04452e26-11d3-463d-72e9-779e14b163cb/volume/rsync-recipes/zlib-1.2.12-on-osx, last modified Mon Apr 18 11:55:00 2022
# ------------------------------------------------

package:
  name: zlib
  version: 1.2.12
source:
  sha256: 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9
  url: http://zlib.net/zlib-1.2.12.tar.gz
build:
  number: '1'
  run_exports:
    - zlib >=1.2.12,<1.3.0a0
  string: h4dc903c_1
requirements:
  build:
    - clang_bootstrap_osx-64 12.0.0 he32ed2a_2
    - cmake-no-system 3.16.5 he9d5cce_2
    - libcxx 12.0.0 h2f01273_0
    - make 4.2.1 h3efe00b_1
  host:
    - ripgrep 12.1.1 0
  run: []
test:
  commands:
    - test -f ${PREFIX}/include/zlib.h
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz.dylib
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: https://zlib.net/manual.html
  home: https://zlib.net/
  license: Zlib
  license_family: Other
  license_file: zlib.h
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - groutr
    - mingwandroid
    - msarahan
    - ocefpaf
