# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/ddc5cdb0-5de4-4b02-7ff1-a3ba6f1334e5/volume/rsync-recipes/python.app-3-python_3.7-on-osx, last modified Fri Oct  1 10:31:09 2021
# ------------------------------------------------

package:
  name: python.app
  version: '3'
build:
  number: '0'
  string: py37hca72f7f_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_23
    - clang 12.0.0 hecd8cb5_2
    - clang-12 12.0.0 default_hfcad0e5_2
    - clang_osx-64 12.0.0 h7ad7729_2
    - clangxx 12.0.0 default_hfcad0e5_2
    - compiler-rt 12.0.0 hd87ff74_2
    - compiler-rt_osx-64 12.0.0 hfb26b64_2
    - ld64_osx-64 530 h70f3046_23
    - ldid 2.1.2 hc000a5c_2
    - libclang-cpp12 12.0.0 default_hfcad0e5_2
    - libcxx 12.0.0 h2f01273_0
    - libllvm12 12.0.0 h9b2ccf5_3
    - llvm-tools 12.0.0 h9b2ccf5_3
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.11 h1de35cc_3
  host:
    - ca-certificates 2021.10.26 hecd8cb5_2
    - libcxx 12.0.0 h2f01273_0
    - libffi 3.3 hb1e8313_2
    - ncurses 6.3 hca72f7f_0
    - openssl 1.1.1l h9ed2024_0
    - python 3.7.11 h88f2d9e_0
    - readline 8.1 h9ed2024_0
    - sqlite 3.36.0 hce871da_0
    - tk 8.6.11 h7bc2e8c_0
    - xz 5.2.5 h1de35cc_0
    - zlib 1.2.11 h1de35cc_3
  run:
    - python >=3.7,<3.8.0a0
test:
  commands:
    - python.app -V
    - pythonw -V
  files:
    - t.py
about:
  home: https://www.python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Proxy on macOS letting Python libraries hook into the GUI event loop
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ChrisBarker-NOAA
    - cpbotha
    - hoechenberger
