# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_clone-9k6hc4w2/recipe, last modified Thu Mar 31 04:13:35 2022
# ------------------------------------------------

package:
  name: sqlite
  version: 3.38.2
source:
  patches: null
  sha256: e7974aa1430bad690a5e9f79a6ee5c8492ada8269dc675875ad0fb747d7cada4
  url: https://www.sqlite.org/2022/sqlite-autoconf-3380200.tar.gz
build:
  ignore_run_exports:
    - ncurses
  number: '0'
  run_exports:
    - sqlite >=3.38.2,<4.0a0
  string: h707629a_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_23
    - clang 12.0.0 hecd8cb5_2
    - clang-12 12.0.0 default_hfcad0e5_2
    - clang_osx-64 12.0.0 h7ad7729_2
    - clangxx 12.0.0 default_hfcad0e5_2
    - compiler-rt 12.0.0 hd87ff74_2
    - compiler-rt_osx-64 12.0.0 hfb26b64_2
    - ld64_osx-64 530 h70f3046_23
    - ldid 2.1.2 h2d21305_2
    - libclang-cpp12 12.0.0 default_hfcad0e5_2
    - libcxx 12.0.0 h2f01273_0
    - libllvm12 12.0.0 h9b2ccf5_3
    - libtool 2.4.6 he9d5cce_1008
    - llvm-tools 12.0.0 h9b2ccf5_3
    - make 4.2.1 h3efe00b_1
    - patch 2.7.6 h1de35cc_1001
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.11 h4dc903c_4
  host:
    - ncurses 6.3 hca72f7f_2
    - readline 8.0 h1de35cc_0
    - zlib 1.2.11 h4dc903c_4
  run:
    - readline >=8.0,<9.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - sqlite3 --version
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine. It is the most used database engine

    in the world.

    '
  dev_url: https://sqlite.org/src/dir?ci=trunk
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: https://www.sqlite.org/docs.html
  home: https://www.sqlite.org/
  license: Unlicense
  license_url: https://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
    - xylar
