# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/da6f10aa-e617-4894-45a9-cfdf5da681c3/volume/rsync-recipes/ruamel_yaml-0.15.100-python_3.7-on-osx, last modified Wed Mar 17 14:08:04 2021
# ------------------------------------------------

package:
  name: ruamel_yaml
  version: 0.15.100
source:
  sha256: 8e42f3067a59e819935a2926e247170ed93c8f0b2ab64526f888e026854db2e4
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.15.100.tar.gz
build:
  number: '0'
  string: py37h9ed2024_0
requirements:
  build:
    - cctools 927.0.2 h5ba7a2e_4
    - clang 10.0.0 default_hf57f61e_0
    - clang_osx-64 10.0.0 h05bbb7f_1
    - clangxx 10.0.0 default_hf57f61e_0
    - compiler-rt 10.0.0 h47ead80_0
    - compiler-rt_osx-64 10.0.0 hbcc88fd_0
    - ld64 450.3 h3c32e8a_4
    - libcxx 10.0.0 1
    - libllvm10 10.0.0 h21ff451_2
    - llvm-openmp 10.0.0 h28b9765_0
    - llvm-tools 10.0.0 h21ff451_2
    - tapi 1000.10.8 ha1b3eb9_0
  host:
    - ca-certificates 2021.1.19 hecd8cb5_1
    - certifi 2020.12.5 py37hecd8cb5_0
    - cython 0.29.22 py37h23ab428_0
    - libcxx 10.0.0 1
    - libffi 3.3 hb1e8313_2
    - ncurses 6.2 h0a44026_1
    - openssl 1.1.1j h9ed2024_0
    - pip 21.0.1 py37hecd8cb5_0
    - python 3.7.10 h88f2d9e_0
    - readline 8.1 h9ed2024_0
    - setuptools 52.0.0 py37hecd8cb5_0
    - sqlite 3.35.1 hce871da_0
    - tk 8.6.10 hb0a8c7a_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h1de35cc_0
    - yaml 0.2.5 haf1e3a3_0
    - zlib 1.2.11 h1de35cc_3
  run:
    - python >=3.7,<3.8.0a0
    - yaml >=0.2.5,<0.3.0a0
test:
  commands:
    - if pip show ruamel.yaml; then exit 1; fi
    - $PYTHON -m pip install ruamel.yaml
    - $PYTHON -c "import ruamel.yaml"
    - pip check
  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml
  requires:
    - pip
about:
  home: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
