# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_clone-hkjilnw9/recipe, last modified Mon Mar 28 07:06:59 2022
# ------------------------------------------------

package:
  name: python
  version: 3.7.13
source:
  - patches:
      - patches/0001-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
      - patches/0003-Add-Anaconda-Distribution-version-logic.patch
      - patches/0004-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0005-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0006-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0008-Support-cross-compiling-byte-code.patch
      - patches/0009-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0010-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0011-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Win32-Do-not-download-externals.patch
      - patches/0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0015-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0016-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0017-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0018-Unvendor-openssl.patch
      - patches/0019-Unvendor-sqlite3.patch
      - patches/0020-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0021-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0022-Use-ranlib-from-env-if-env-variable-is-set.patch
    sha256: 99f106275df8899c3e8cb9d7c01ce686c202ef275953301427194693de5bef84
    url: https://www.python.org/ftp/python/3.7.13/Python-3.7.13.tar.xz
build:
  binary_has_prefix_files:
    - lib/libpython3.7.*.1.0
    - lib/libpython3.dylib
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - bzip2
    - libcxx
    - libcxxabi
  missing_dso_whitelist: null
  no_link: null
  number: '0'
  script_env:
    - PY_INTERP_DEBUG
    - PY_INTERP_LINKAGE_NATURE
  string: hdfd78df_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_23
    - clang 12.0.0 hecd8cb5_2
    - clang-12 12.0.0 default_hfcad0e5_2
    - clang_osx-64 12.0.0 h7ad7729_2
    - clangxx 12.0.0 default_hfcad0e5_2
    - clangxx_osx-64 12.0.0 he0c6f94_2
    - compiler-rt 12.0.0 hd87ff74_2
    - compiler-rt_osx-64 12.0.0 hfb26b64_2
    - ld64_osx-64 530 h70f3046_23
    - ldid 2.1.2 h2d21305_2
    - libclang-cpp12 12.0.0 default_hfcad0e5_2
    - libcxx 12.0.0 h2f01273_0
    - libiconv 1.16 h1de35cc_0
    - libllvm12 12.0.0 h9b2ccf5_3
    - llvm-tools 12.0.0 h9b2ccf5_3
    - make 4.2.1 h3efe00b_1
    - patch 2.7.6 h1de35cc_1001
    - pkg-config 0.29.2 h3efe00b_8
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.11 h4dc903c_4
  host:
    - bzip2 1.0.8 h1de35cc_0
    - ca-certificates 2022.3.18 hecd8cb5_0
    - libcxx 12.0.0 h2f01273_0
    - libffi 3.3 hb1e8313_2
    - ncurses 6.3 hca72f7f_2
    - openssl 1.1.1n hca72f7f_0
    - readline 8.0 h1de35cc_0
    - sqlite 3.37.2 h707629a_0
    - tk 8.6.11 h7bc2e8c_0
    - xz 5.2.5 h1de35cc_0
    - zlib 1.2.11 h4dc903c_4
  run:
    - libffi >=3.3,<3.4.0a0
    - ncurses >=6.3,<7.0a0
    - openssl >=1.1.1n,<1.1.2a
    - readline >=8.0,<9.0a0
    - sqlite >=3.37.2,<4.0a0
    - tk >=8.6.11,<8.7.0a0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd distutils.cext
    - python setup.py install -v -v
    - python -v -v -v -c "import greet"
    - python -v -v -v -c "import greet; greet.greet('Python user')" | rg "Hello Python"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd processpoolexecutor-max_workers-61
    - python ppe.py
    - popd
    - pushd cmake
    - popd
    - popd
  files:
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils.cext/*
    - tests/distutils/*
    - tests/prefix-replacement/*
    - tests/processpoolexecutor-max_workers-61/*
  requires:
    - clang_osx-64 12.*
    - clangxx_osx-64 12.*
    - cmake
    - cython
    - ninja
    - ripgrep
    - setuptools
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
